---
driver:
  name: docker

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.5
    driver_config:
      forward:
      - 27017:27017

suites:
  - name: default
    run_list: 
      - recipe[otter-mongodb::default]
    attributes:

