name 'otter-mongodb'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures otter-mongodb'
long_description 'Installs/Configures otter-mongodb'
version '0.2.0'
depends 'yum', '~> 3.11.0'
depends 'selinux', '= 0.5.0'
